### ISSUE TITLE
Running Application Getting Log message Could not load Finalizer in its own class loader

### ISSUE THREAD

**Issue by vikasgrover33** [Stuart-campbell/RushOrm#102]
Could not load Finalizer in its own class loader.Loading Finalizer in the current class loader instead. As a result, you will not be ableto garbage collect this class loader. To support reclaiming this class loader, eitherresolve the underlying issue, or move Google Collections to your system class path.
                                                                               java.io.FileNotFoundException: com/google/common/base/internal/Finalizer.class
                                                                                   at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:308)
                                                                                   at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.loadFinalizer(FinalizableReferenceQueue.java:292)
                                                                                   at com.google.common.base.FinalizableReferenceQueue.loadFinalizer(FinalizableReferenceQueue.java:212)
                                                                                   at com.google.common.base.FinalizableReferenceQueue.<clinit>(FinalizableReferenceQueue.java:136)
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.Class.forName(Class.java:324)
                                                                                   at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:58)
                                                                                   at co.uk.rushorm.android.AndroidRushClassFinder.getRushClasses(AndroidRushClassFinder.java:45)
                                                                                   at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:36)
                                                                                   at co.uk.rushorm.core.RushCore.loadAnnotationCache(RushCore.java:462)
                                                                                   at co.uk.rushorm.core.RushCore.initialize(RushCore.java:122)
                                                                                   at co.uk.rushorm.core.RushCore.initialize(RushCore.java:80)
                                                                                   at com.arkaa.app.doctor.application.DoctorApplicationClass.onCreate(DoctorApplicationClass.java:60)
                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
                                                                                   at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by Stuart-campbell** [comment]
Hi,

The class loading is known to have a few issues when an app has other dependencies. Looking for a elegant solution to it.

In the mean time this will resolve your issue.

http://www.rushorm.com/advanced.html#Troubleshooting

Thanks
