### ISSUE TITLE
Column not found error.

### ISSUE THREAD

**Issue by herrmartell** [Stuart-campbell/RushOrm#118]
As I posted on StackOverflow 

[http://stackoverflow.com/questions/38311995/app-crashing-once-in-the-google-play-store-but-never-on-android-studio?noredirect=1#comment64041306_38311995](url)

The DB is crashing my app because it says type_of_check doesn't exist. As you can see on my post there, the field does exist. 

I also get this:

`android.database.sqlite.SQLiteException: no such column: type_of_check (code 1): , while compiling: SELECT * from rush_com_avena_avenafit_a_b WHERE type_of_check='1' AND check_date='2016-07-11'    ;`

I already tried changing my db version:

`
        <meta-data
            android:name="Rush_db_version"
            android:value="2" />`

Setting debug mode:

`
        <meta-data
            android:name="Rush_debug"
            android:value="true" />`

And adding this suggestion which I have no idea what it does:

`<meta-data android:name="Rush_classes_package"
            android:value="co.uk.rushexample" />``

Could anyone help me fixing this?

**Comment by herrmartell** [comment]
Forgot to mention, I also added these two:

`-keep public class * extends co.uk.rushorm.core.Rush { *; }`
`-keep public class * extends co.uk.rushorm.core.Rush { *; }` 

Since I use minify with ProGuard. But those lines did nothing for me.

**Comment by Stuart-campbell** [comment]
Hi,

Definitely looks like a ProGuard issue.

Try adding this line.

     -keep public class * implements co.uk.rushorm.core.Rush { *; }

Thanks

**Comment by herrmartell** [comment]
Sorry, my previous post was meant to read:

`-keep public class * implements co.uk.rushorm.core.Rush { *; }` 
`-keep public class * extends co.uk.rushorm.core.Rush { *; }`

None are doing anything for me. Also tried with:

`-keep public class * implements co.uk.rushorm.core.RushObject { *; }` 
`-keep public class * extends co.uk.rushorm.core.RushObject { *; }`

But didn't work either.

**Comment by Stuart-campbell** [comment]
Hi,

Just updated the example app to use proguard 

    -keep public class * implements co.uk.rushorm.core.Rush { *; }

Just this one line worked for me.

What does your build.gradle file look like?

Thanks

**Comment by herrmartell** [comment]
Here's the project build/gradle 

> buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://dl.bintray.com/intercom/intercom-maven' }
        maven { url "http://dl.bintray.com/pixplicity/maven" }
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
        maven { url 'https://dl.bintray.com/intercom/intercom-maven' }
        maven { url "http://dl.bintray.com/pixplicity/maven" }
        maven { url "https://jitpack.io" }
        maven { url "http://maven.rushorm.com" }
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
task stripResources << {
    println "Custom resource stripping in: $buildDir"
    delete fileTree(dir: "$buildDir", include: "**/layout/confirmation_activity_layout.xml")
    delete fileTree(dir: "$buildDir", include: "**/layout/watch_card_content.xml")
    delete fileTree(dir: "$buildDir", include: "**/common_signin*.png")
    delete fileTree(dir: "$buildDir", include: "**/drawable/common_signin*.xml")
    delete fileTree(dir: "$buildDir", include: "**/generic_confirmation*.png")
    delete fileTree(dir: "$buildDir", include: "**/drawable/confirmation_*.xml")
    delete fileTree(dir: "$buildDir", include: "**/drawable/card_background.xml")
    delete fileTree(dir: "$buildDir", include: "**/card_frame*.png")
    delete fileTree(dir: "$buildDir", include: "**/go_to*.png")
    delete fileTree(dir: "$buildDir", include: "**/drawable/go_to_*.xml")
    delete fileTree(dir: "$buildDir", include: "**/ic_plusone*.png")
    delete fileTree(dir: "$buildDir", include: "**/powered_by_google*.png")
}
tasks.whenTaskAdded { task ->
    if (task.name == 'processReleaseManifest') {
        task.dependsOn stripResources
    }
}

And here's my app build/gradle

> apply plugin: "com.android.application"
apply plugin: "com.neenbedankt.android-apt"
android {
    signingConfigs {
    }
    compileSdkVersion 23
    buildToolsVersion '24'
    defaultConfig {
        applicationId "com.avena.avenafit"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 13
        versionName "1.1.1"
        resConfigs "es"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            zipAlignEnabled true
        }
        debug {
            minifyEnabled true
            shrinkResources true
        }
    }
    splits {
        density {
            enable true
            exclude "ldpi", "tvdpi", "xxxhdpi", "mdpi"
            compatibleScreens 'small', 'normal', 'large', 'xlarge'
        }
    }
}
apt {
    arguments {
        resourcePackageName android.defaultConfig.applicationId
        androidManifestFile variant.outputs[0]?.processResources?.manifestFile
        logLevel 'INFO'
        logFile '/var/log/aa.log'
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    // Android Annotations
    apt "org.androidannotations:androidannotations:4.0.0"
    compile 'org.androidannotations:androidannotations-api:4.0.0'
    // Google Cloud Messaging
    compile 'com.google.android.gms:play-services-gcm:9.2.0'
    // Android Volley
    compile 'com.android.volley:volley:1.0.0'
    // Android Support
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.android.support:cardview-v7:23.3.0'
    compile 'com.android.support:recyclerview-v7:23.3.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha3'
    // Intercom
    compile 'io.intercom.android:intercom-sdk-base:1.1.21@aar'
    compile 'io.intercom.android:intercom-sdk-gcm:1.1.21@aar'
    // Easy Preferences
    compile 'com.pixplicity.easyprefs:library:1.8.1@aar'
    // MixPanel
    compile 'com.mixpanel.android:mixpanel-android:4.9.1'
    // RushORM
    compile 'co.uk.rushorm:rushandroid:1.2.0'
}
apply plugin: "com.google.gms.google-services"

Sorry I pasted both, but I was not sure which one you needed to see.

**Comment by herrmartell** [comment]
Curses! I just noticed my debug buildType isn't checking the Proguard config. I'm about to try that.

**Comment by Stuart-campbell** [comment]
No worries, let me know if that does the trick.

Thanks

**Comment by herrmartell** [comment]
Well, it stopped crashing on load, but now I get this

>java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                                        at com.avena.avenafit.dashboard.g.K(Unknown Source)
                                                                        at com.avena.avenafit.dashboard.g.a(Unknown Source)
                                                                        at android.support.v4.app.Fragment.c(Unknown Source)
                                                                        at android.support.v4.app.af.a(Unknown Source)
                                                                        at android.support.v4.app.ab.a(Unknown Source)
                                                                        at android.support.v4.app.w.onMenuItemSelected(Unknown Source)
                                                                        at android.support.v7.a.ag.onMenuItemSelected(Unknown Source)
                                                                        at android.support.v7.view.n.onMenuItemSelected(Unknown Source)
                                                                        at android.support.v7.view.n.onMenuItemSelected(Unknown Source)
                                                                        at android.support.v7.a.bl.a(Unknown Source)
                                                                        at android.support.v7.widget.gn.a(Unknown Source)
                                                                        at android.support.v7.widget.x.a(Unknown Source)
                                                                        at android.support.v7.view.menu.i.a(Unknown Source)
                                                                        at android.support.v7.view.menu.m.b(Unknown Source)
                                                                        at android.support.v7.view.menu.i.a(Unknown Source)
                                                                        at android.support.v7.view.menu.i.a(Unknown Source)
                                                                        at android.support.v7.widget.ActionMenuView.a(Unknown Source)
                                                                        at android.support.v7.view.menu.ActionMenuItemView.onClick(Unknown Source)
                                                                        at android.view.View.performClick(View.java:5204)
                                                                        at android.view.View$PerformClick.run(View.java:21158)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Stuart-campbell** [comment]
Have you done a clean install since updating the pro guard rules. All the database table and column names will have changed. So may just be that.

**Comment by herrmartell** [comment]
Seems to be working now... I will keep testing. I wonder what caused this in the first place. Yesterday everything was working A-OK.

**Comment by Stuart-campbell** [comment]
Glad its sorted.

Thanks
