### ISSUE TITLE
RushTableMissingEmptyConstructorException

### ISSUE THREAD

**Issue by Luisfermp18** [Stuart-campbell/RushOrm#120]
Hi,

Sorry for my English. I have a problem when i try to find elements from my database. I have the next models class to persist:

```
public class Book extends RushObject{
    private String bookName;
    private String bookEdition;
    private Author author;

    @RushList(classType = Author.class)
    private List<Author> bookColaborators;


    public Book(String bookName, String bookEdition, Author author, List<Author> bookColaborators) {
        this.bookName = bookName;
        this.bookEdition = bookEdition;
        this.author = author;
        this.bookColaborators = bookColaborators;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getBookEdition() {
        return bookEdition;
    }

    public void setBookEdition(String bookEdition) {
        this.bookEdition = bookEdition;
    }

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

    public List<Author> getBookColaborators() {
        return bookColaborators;
    }

    public void setBookColaborators(List<Author> bookColaborators) {
        this.bookColaborators = bookColaborators;
    }

    @Override
    public String toString() {
        String colaborators = "[";
        for(int i = 0; i < bookColaborators.size();i++){
            colaborators.concat(bookColaborators.get(i).toString());
        }
        colaborators.concat("]");
        return "Book{" +
                "bookName='" + bookName + '\'' +
                ", bookEdition='" + bookEdition + '\'' +
                ", author=" + author +
                ", bookColaborators=" + colaborators +
                '}';
    }


    @Override
    public void save() { RushCore.getInstance().save(this); }
    @Override
    public void save(RushCallback callback) { RushCore.getInstance().save(this, callback); }
    @Override
    public void delete() { RushCore.getInstance().delete(this); }
    @Override
    public void delete(RushCallback callback) { RushCore.getInstance().delete(this, callback); }
    @Override
    public String getId() { return RushCore.getInstance().getId(this); }
}
```

and the next one:

```
public class Author extends RushObject {
    private String name;
    private String surname;
    private Date birthDate;


    public Author(String name, String surname, Date birthDate) {
        this.name = name;
        this.surname = surname;
        this.birthDate = birthDate;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }



    @Override
    public void save() { RushCore.getInstance().save(this); }
    @Override
    public void save(RushCallback callback) { RushCore.getInstance().save(this, callback); }
    @Override
    public void delete() { RushCore.getInstance().delete(this); }
    @Override
    public void delete(RushCallback callback) { RushCore.getInstance().delete(this, callback); }
    @Override
    public String getId() { return RushCore.getInstance().getId(this); }
}
```

In my MainActivity.java i have the next code:

```
public void insertElements(View v){
        for (int i = 0; i < 15; i++){
            List<Author> collaboratorsAuthors = new ArrayList<>();
            for (int j = 0 ; j < 4; j++){
                collaboratorsAuthors.add(new Author("Collaborator nº"+i+"-"+j, "SurCollaborator nº"+i+"-"+j,new Date()));
            }
            Book insertion = new Book("Libro nº"+i, "Edition" + i
                    ,new Author("Pedro "+i,"Almaraz"+i,new Date()),collaboratorsAuthors);
            Log.d("RUSH_ORM_DEBUGGER","INSERTION Nº"+i+"/"+ insertion.toString());
            insertion.save();
        }
    }

    public void massiveQuery(View v){
        List<Book> objects = new RushSearch().find(Book.class);
        for (int i = 0; i < objects.size(); i++){
            Log.d("RUSH_ORM_DEBUGGER","MASSIVE QUERY ELEMENT Nº"+i+"/"+ objects.get(i).toString());
        }
    }


    public void idQuery(View v){
        Book table = new RushSearch().whereId("1").findSingle(Book.class);
        Log.d("RUSH_ORM_DEBUGGER", "ID QUERY: " +table.toString());
    }

    public void idDelete(View v){
        Book table = new RushSearch().whereId("4").findSingle(Book.class);
        Log.d("RUSH_ORM_DEBUGGER", "ID DELETE BEFORE: " +table.toString());
        table.delete();
        table = new RushSearch().whereId("4").findSingle(Book.class);
        Log.d("RUSH_ORM_DEBUGGER", "ID DELETE AFTER: " +table.toString());
    }


    public void massiveDelete(View v){
        List<Book> objects = new RushSearch().find(Book.class);
        Log.d("RUSH_ORM_DEBUGGER","MASSIVE DELETE ELEMENT SIZE BEFORE: "+ objects.size());
        for (int i = 0; i < objects.size(); i++){
            Log.d("RUSH_ORM_DEBUGGER","MASSIVE DELETE ELEMENT Nº"+i+"/"+ objects.get(i).toString());
            objects.get(i).delete();
        }
        objects = new RushSearch().find(Book.class);
        Log.d("RUSH_ORM_DEBUGGER","MASSIVE DELETE ELEMENT SIZE AFTER: "+ objects.size());
    }

```
These methods are executed when I click in a button. Storage does not give me any problems, since it runs and does not fail. But when I try to get the information the following code, I get the error that follows:

` List<Book> objects = new RushSearch().find(Book.class);`

or
`Book table = new RushSearch().whereId("1").findSingle(Book.class);`

THE ERROR:

```
08-12 12:45:58.105 2751-2751/freakdeveloper.lfmelonp.org.prueba_rush E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: freakdeveloper.lfmelonp.org.prueba_rush, PID: 2751
                                                                                       java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                           at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                                           at android.view.View.performClick(View.java:5198)
                                                                                           at android.view.View$PerformClick.run(View.java:21147)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                                           at android.view.View.performClick(View.java:5198) 
                                                                                           at android.view.View$PerformClick.run(View.java:21147) 
                                                                                           at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                        Caused by: co.uk.rushorm.core.exceptions.RushTableMissingEmptyConstructorException: freakdeveloper.lfmelonp.org.prueba_rush.models.Book Implement: Book(){}
                                                                                           at co.uk.rushorm.core.RushCore.load(RushCore.java:640)
                                                                                           at co.uk.rushorm.core.RushCore.load(RushCore.java:257)
                                                                                           at co.uk.rushorm.core.RushSearch.find(RushSearch.java:41)
                                                                                           at freakdeveloper.lfmelonp.org.prueba_rush.activities.MainActivity.massiveQuery(MainActivity.java:43)
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                                           at android.view.View.performClick(View.java:5198) 
                                                                                           at android.view.View$PerformClick.run(View.java:21147) 
                                                                                           at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

Thanks in advance. Excuse my English!

A cordial greeting

**Comment by Stuart-campbell** [comment]
Hi,

All your objects require an empty contrcuter as Rush uses reflation to create them.

Just add 

    public Book(){}

and

    public Author(){}

To your classes.

On a side note you do not need to include these methods in your classes

    @Override
    public void save() { RushCore.getInstance().save(this); }
    @Override
    public void save(RushCallback callback) { RushCore.getInstance().save(this, callback); }
    @Override
    public void delete() { RushCore.getInstance().delete(this); }
    @Override
    public void delete(RushCallback callback) { RushCore.getInstance().delete(this, callback); }
    @Override
    public String getId() { return RushCore.getInstance().getId(this); }

They are only required if you implement Rush instead of extend RushObject.

Thanks
