### ISSUE TITLE
List<String> List<Integer> not a rush list cause crash

### ISSUE THREAD

**Issue by Pascal66** [Stuart-campbell/RushOrm#140]
`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String co.uk.rushorm.core.AnnotationCache.getTableName()' on a null object reference
        at co.uk.rushorm.core.implementation.ReflectionTableStatementGenerator.generateStatements(ReflectionTableStatementGenerator.java:50)
        at co.uk.rushorm.core.RushCore.createTables(RushCore.java:469)
        at co.uk.rushorm.core.RushCore.access$200(RushCore.java:39)
        at co.uk.rushorm.core.RushCore$1.run(RushCore.java:130)`

**Comment by Pascal66** [comment]
[Storing lists of boxed primitives/Strings](https://stackoverflow.com/questions/35024271/storing-lists-of-boxed-primitives-strings[](url))
