### ISSUE TITLE
Annotation error ? no Rushlist created in db

### ISSUE THREAD

**Issue by Pascal66** [Stuart-campbell/RushOrm#141]
`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String co.uk.rushorm.core.AnnotationCache.getTableName()' on a null object reference
        at co.uk.rushorm.core.implementation.ReflectionTableStatementGenerator.generateStatements(ReflectionTableStatementGenerator.java:50)
        at co.uk.rushorm.core.RushCore.createTables(RushCore.java:469)
        at co.uk.rushorm.core.RushCore.access$200(RushCore.java:39)
        at co.uk.rushorm.core.RushCore$1.run(RushCore.java:130)`

**Comment by Pascal66** [comment]
If I restart (with the bad db) I have :
`    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String co.uk.rushorm.core.AnnotationCache.getTableName()' on a null object reference
        at co.uk.rushorm.core.implementation.ReflectionUpgradeManager.addJoinMappingIfRequired(ReflectionUpgradeManager.java:223)
        at co.uk.rushorm.core.implementation.ReflectionUpgradeManager.potentialMapping(ReflectionUpgradeManager.java:208)
        at co.uk.rushorm.core.implementation.ReflectionUpgradeManager.upgrade(ReflectionUpgradeManager.java:71)
        at co.uk.rushorm.core.RushCore.upgrade(RushCore.java:480)
        at co.uk.rushorm.core.RushCore.access$300(RushCore.java:39)
        at co.uk.rushorm.core.RushCore$1.run(RushCore.java:132)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by Pascal66** [comment]
Just missing the boring classList
