### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by EmanueleHB** [Stuart-campbell/RushOrm#17]
Hi i just implemented your library but it crashes on startup with this error. I followed the realm to initialize.
```java
03-25 16:41:19.913  27702-27702/com.lord.emanuele.orarioscolastico E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.lord.emanuele.orarioscolastico, PID: 27702
    java.lang.RuntimeException: Unable to create application com.lord.emanuele.orarioscolastico.DiaryApp: java.lang.NullPointerException: println needs a message
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: println needs a message
            at android.util.Log.println_native(Native Method)
            at android.util.Log.e(Log.java:232)
            at co.uk.rushorm.android.AndroidLogger.logError(AndroidLogger.java:37)
            at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:60)
            at co.uk.rushorm.android.AndroidRushClassFinder.getRushClasses(AndroidRushClassFinder.java:45)
            at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:36)
            at co.uk.rushorm.core.RushCore.loadAnnotationCache(RushCore.java:334)
            at co.uk.rushorm.core.RushCore.initialize(RushCore.java:85)
            at co.uk.rushorm.core.RushCore.initialize(RushCore.java:63)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:38)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:23)
            at com.lord.emanuele.orarioscolastico.DiaryApp.onCreate(DiaryApp.java:16)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by Stuart-campbell** [comment]
Hi,

Does your project have a lot of other dependencies?

I think you have the same issue #4 So likely can be solved as suggested on that issue. I thought I had resolved it but looks like the throwable i'm catching has a null error message, which is breaking the logger.

I will put a null check in the logger.

Cheers

**Comment by EmanueleHB** [comment]
Yup, there's quite a lot. 
Okay, I will try soon. 

Thanks

**Comment by Stuart-campbell** [comment]
I have added a null check to the logger in v1.1.2 so this should be resolved thanks.

**Comment by EmanueleHB** [comment]
Great, thank you.
