### ISSUE TITLE
NullPointerException because of save

### ISSUE THREAD

**Issue by PaulineBAUDOUIN** [Stuart-campbell/RushOrm#19]
Hi ! 
I'm trying to make my project work with RushORM so here is my OnCreate function in the MainActivity:

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        RushAndroid.initialize(getApplicationContext());

        ImageButton aff_maquettes = (ImageButton) (findViewById(R.id.aff_maq));
        aff_maquettes.setOnClickListener(this);

        Maquette m1 = new Maquette();
        m1.descritpion = "test";
        m1.save();
    }

When I try to launch it on my tablet, the app crashes and I get the NullPointerException. It seems that it is because of the m1.save().

Can anyone help me ? :) 

PS: please ask if you need another part of my code

**Comment by Stuart-campbell** [comment]
Hi,

First point you should really call 

    RushAndroid.initialize(getApplicationContext());

in your application class calling it in your activity is likely to cause it to be called twice.

Call you add the full log print out of the crash hopefully give a better clue to the cause.

Thanks

**Comment by PaulineBAUDOUIN** [comment]
Thanks for answering ! Here it is:

04-09 09:31:04.429  10086-10086/focalys.android_avh E/RushOrm﹕ android.support.v4.view.ViewCompat$JbMr1ViewCompatImpl
04-09 09:31:04.429  10086-10086/focalys.android_avh E/RushOrm﹕ android.support.v4.view.accessibility.AccessibilityNodeInfoCompat$AccessibilityNodeInfoApi22Impl
04-09 09:31:04.429  10086-10086/focalys.android_avh E/RushOrm﹕ android.support.v4.view.ViewCompat$KitKatViewCompatImpl
04-09 09:31:04.429  10086-10086/focalys.android_avh E/RushOrm﹕ android.support.v4.view.ViewCompat$Api21ViewCompatImpl
04-09 09:31:04.449  10086-10086/focalys.android_avh D/dalvikvm﹕ GC_FOR_ALLOC freed 1243K, 31% free 5107K/7352K, paused 4ms, total 4ms
04-09 09:31:04.449  10086-10086/focalys.android_avh D/AndroidRuntime﹕ Shutting down VM
04-09 09:31:04.449  10086-10086/focalys.android_avh W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4331d1a0)
04-09 09:31:04.459  10086-10086/focalys.android_avh E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: focalys.android_avh, PID: 10086
    java.lang.RuntimeException: Unable to start activity ComponentInfo{focalys.android_avh/focalys.android_avh.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5653)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at co.uk.rushorm.core.implementation.Insert.ReflectionSaveStatementGenerator.generateSaveOrUpdate(ReflectionSaveStatementGenerator.java:84)
            at co.uk.rushorm.core.implementation.Insert.ReflectionSaveStatementGenerator.generateSaveOrUpdate(ReflectionSaveStatementGenerator.java:50)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:381)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:139)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:134)
            at co.uk.rushorm.core.RushObject.save(RushObject.java:12)
            at focalys.android_avh.MainActivity.onCreate(MainActivity.java:29)
            at android.app.Activity.performCreate(Activity.java:5541)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5653)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Stuart-campbell** [comment]
Did you move initialize to the an application class or singleton? Just to confirm are you using multiple dex files?

The null pointer is in the annotation cache used so there is no repetition of reflection. I can only think that could happen if initialize is recalled during a save or if the class was not found in the dex.

**Comment by PaulineBAUDOUIN** [comment]
I do have an application class but I don't really understand how it is supposed to work.
Here it is:

    public class Appli extends Application {
        @Override
        public void onCreate() {
            super.onCreate();
    
            RushAndroid.initialize(getApplicationContext());

        }
    }

I also have deleted the call of initialization in the main activity.
Is that enough ?

**Comment by Stuart-campbell** [comment]
Hopefully that should be. You do also need to set the name of the Application in your manifest to your custom one.

    <application
        android:name="{package}. Appli"
       >
    ...

    </application>

**Comment by PaulineBAUDOUIN** [comment]
Ok I made it ! I now have a new exception. Here is the log:

04-09 11:23:51.329  13065-13065/focalys.android_avh E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: focalys.android_avh, PID: 13065
    java.lang.RuntimeException: Unable to start activity ComponentInfo{focalys.android_avh/focalys.android_avh.MainActivity}: co.uk.rushorm.core.exceptions.RushSqlException: This is most likely caused by a change in data structure or new RushObject.
    This issue should be resolved by a database migration.
    This can be done by updating db version number in the manifest or setting Rush in debug mode.
    To set Rush in debug mode add this to your manifest file - <meta-data android:name="Rush_debug" android:value="true" />
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
            at android.app.ActivityThread.access$900(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5653)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: co.uk.rushorm.core.exceptions.RushSqlException: This is most likely caused by a change in data structure or new RushObject.
    This issue should be resolved by a database migration.
    This can be done by updating db version number in the manifest or setting Rush in debug mode.
    To set Rush in debug mode add this to your manifest file - <meta-data android:name="Rush_debug" android:value="true" />
            at co.uk.rushorm.android.AndroidRushStatementRunner.runRaw(AndroidRushStatementRunner.java:42)
            at co.uk.rushorm.core.RushCore$10.createdOrUpdateStatement(RushCore.java:390)
            at co.uk.rushorm.core.implementation.Insert.SqlBulkInsertGenerator$2.doAction(SqlBulkInsertGenerator.java:116)
            at co.uk.rushorm.core.implementation.ReflectionUtils.doLoop(ReflectionUtils.java:67)
            at co.uk.rushorm.core.implementation.Insert.SqlBulkInsertGenerator.createOrUpdateObjects(SqlBulkInsertGenerator.java:80)
            at co.uk.rushorm.core.implementation.Insert.ReflectionSaveStatementGenerator.createOrUpdateObjects(ReflectionSaveStatementGenerator.java:171)
            at co.uk.rushorm.core.implementation.Insert.ReflectionSaveStatementGenerator.generateSaveOrUpdate(ReflectionSaveStatementGenerator.java:55)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:381)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:139)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:134)
            at co.uk.rushorm.core.RushObject.save(RushObject.java:12)
            at focalys.android_avh.MainActivity.onCreate(MainActivity.java:29)
            at android.app.Activity.performCreate(Activity.java:5541)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
            ... 11 more

**Comment by PaulineBAUDOUIN** [comment]
Ok I managed to fix the problem. I added the meta-data lines in the Manifest and it worked ! Thank you very much for your help and for your ORM !

**Comment by Stuart-campbell** [comment]
No problem I may look at some new throwables with helpful messages for the future.

Thanks
