### ISSUE TITLE
RushAndroid.initialize fails with error DatatypeConfigurationException

### ISSUE THREAD

**Issue by nooruls143** [Stuart-campbell/RushOrm#3]
Hi,
I added the RushAndroid.initialize(getApplicationContext()); in the Application onCreate method and I get the following exception:

    02-12 00:16:10.857  11910-11910/com.rayat.pricewiz E/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: com.rayat.pricewiz, PID: 11910
        java.lang.ExceptionInInitializerError
                at java.lang.Class.classForName(Native Method)
                at java.lang.Class.forName(Class.java:251)
                at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:56)
                at co.uk.rushorm.android.AndroidRushClassFinder.getDomainClasses(AndroidRushClassFinder.java:43)
                at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:34)
                at co.uk.rushorm.core.RushCore.createTables(RushCore.java:184)
                at co.uk.rushorm.core.RushCore.initialize(RushCore.java:62)
                at co.uk.rushorm.core.RushCore.initialize(RushCore.java:53)
                at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:35)
                at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:21)
                at com.rayat.pricewiz.GlobalApplication.onCreate(GlobalApplication.java:34)
                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
                at android.app.ActivityThread.access$1600(ActivityThread.java:161)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:157)
                at android.app.ActivityThread.main(ActivityThread.java:5356)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:515)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                at dalvik.system.NativeStart.main(Native Method)
         Caused by: java.lang.RuntimeException: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found
                at org.codehaus.jackson.map.ext.CoreXMLDeserializers.<clinit>(CoreXMLDeserializers.java:40)
                at java.lang.Class.classForName(Native Method)
                at java.lang.Class.forName(Class.java:251)
                at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:56)
                at co.uk.rushorm.android.AndroidRushClassFinder.getDomainClasses(AndroidRushClassFinder.java:43)
                at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:34)
                at co.uk.rushorm.core.RushCore.createTables(RushCore.java:184)
                at co.uk.rushorm.core.RushCore.initialize(RushCore.java:62)
                at co.uk.rushorm.core.RushCore.initialize(RushCore.java:53)
                at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:35)
                at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:21)
                at com.rayat.pricewiz.GlobalApplication.onCreate(GlobalApplication.java:34)
                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
                at android.app.ActivityThread.access$1600(ActivityThread.java:161)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:157)
                at android.app.ActivityThread.main(ActivityThread.java:5356)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:515)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                at dalvik.system.NativeStart.main(Native Method)
         Caused by: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found
                at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:106)
                at org.codehaus.jackson.map.ext.CoreXMLDeserializers.<clinit>(CoreXMLDeserializers.java:38)
                at java.lang.Class.classForName(Native Method)
                at java.lang.Class.forName(Class.java:251)
                at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:56)
                at co.uk.rushorm.android.AndroidRushClassFinder.getDomainClasses(AndroidRushClassFinder.java:43)
                at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:34)
                at co.uk.rushorm.core.RushCore.createTables(RushCore.java:184)
                at co.uk.rushorm.core.RushCore.initialize(RushCore.java:62)
                at co.uk.rushorm.core.RushCore.initialize(RushCore.java:53)
                at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:35)
                at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:21)
                at com.rayat.pricewiz.GlobalApplication.onCreate(GlobalApplication.java:34)
                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
                at android.app.ActivityThread.access$1600(ActivityThread.java:161)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:157)
                at android.app.ActivityThread.main(ActivityThread.java:5356)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:515)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                at dalvik.system.NativeStart.main(Native Method)
         Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl" on path: DexPathList[[zip file "/data/app/com.rayat.pricewiz-3.apk"],nativeLibraryDirectories=[/data/app-lib/com.rayat.pricewiz-3, /vendor/lib, /system/lib]]
                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                at javax.xml.datatype.FactoryFinder.newInstance(FactoryFinder.java:138)
                at javax.xml.datatype.FactoryFinder.find(FactoryFinder.java:219)
                at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:99)
                at org.codehaus.jackson.map.ext.CoreXMLDeserializers.<clinit>(CoreXMLDeserializers.java:38)
                at java.lang.Class.classForName(Native Method)
                at java.lang.Class.forName(Class.java:251)
                at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:56)
                at co.uk.rushorm.android.AndroidRushClassFinder.getDomainClasses(AndroidRushClassFinder.java:43)
                at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:34)
                at co.uk.rushorm.core.RushCore.createTables(RushCore.java:184)
                at co.uk.rushorm.core.RushCore.initialize(RushCore.java:62)
                at co.uk.rushorm.core.RushCore.initialize(RushCore.java:53)
                at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:35)
                at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:21)
                at com.rayat.pricewiz.GlobalApplication.onCreate(GlobalApplication.java:34)
                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
                at android.app.ActivityThread.access$1600(ActivityThread.java:161)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:157)
                at android.app.ActivityThread.main(ActivityThread.java:5356)
                at java.lang.reflect.Method.invokeNative(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:515)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                at dalvik.system.NativeStart.main(Native Method)

I added the following config in the AndroidManifest.xml file

    <meta-data android:name="Rush_db_version" android:value="1" />
    <meta-data android:name="Rush_db_name" android:value="rush.db" />
    <meta-data android:name="Rush_debug" android:value="false" />
    <meta-data android:name="Rush_requires_table_annotation" android:value="false" />

**Comment by Stuart-campbell** [comment]
Are you using multiple dex files? 

The problem seems to be loading "org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl" to check if it's an instance of Rush.

Ill need to look into this one a bit more. Might just need better error handling.

Quick fix would be to add this initialize yourself

     public static void initialize(Context context, final List<Class> classes) {
        Context applicationContext = context.getApplicationContext();

        RushConfig rushConfig = new AndroidRushConfig(applicationContext);
        RushStringSanitizer rushStringSanitizer = new AndroidRushStringSanitizer();
        RushStatementRunner statementRunner = new AndroidRushStatementRunner(applicationContext, rushConfig.dbName(), rushConfig.dbVersion());
        RushQueProvider queProvider = new AndroidRushQueProvider();
        Logger logger = new AndroidLogger();

        RushCore.initialize(new RushClassFinder() {
            @Override
            public List<Class> findClasses(RushConfig rushConfig) {
                return classes;
            }
        }, statementRunner, queProvider, rushConfig, rushStringSanitizer, logger, new ArrayList<RushColumn>());
    }

Then call as below. (This would actually be faster in the long run, just need to make sure you add all the classes you need)

    List<Class> classes = new ArrayList<>();
    classes.add(FirstRushClass.class);
    classes.add(SecondRushClass.class);
    initialize(getContext(), classes);

**Comment by Stuart-campbell** [comment]
I have updated main to 0.6.0, this update should catch all exceptions when loading classes, which will hopefully fix that crash, although I do wonder if it comes from a deeper problem with your dependencies.

Thanks
