### ISSUE TITLE
Make sure the cursor is initialized correctly

### ISSUE THREAD

**Issue by PaulineBAUDOUIN** [Stuart-campbell/RushOrm#37]
Hi, 
I think I have a new problem. I'm trying to make
``` Java
Gabarit gabTest = new RushSearch().whereEqual("identifier", idGab).findSingle(Gabarit.class);
```
I have the exception:

```Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.```

but I don't understand why it doesn't work...
Any idea ?

**Comment by Stuart-campbell** [comment]
Could you share the full stack trace?

Are you saving a long/int which has never been set to a value?

**Comment by PaulineBAUDOUIN** [comment]
Thank you for answering so fast ! 
Here is the stack trace:
```
9887-9887/focalys.avh_android W/System.err﹕ Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at android.database.CursorWindow.nativeGetString(Native Method)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at android.database.CursorWindow.getString(CursorWindow.java:439)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.android.AndroidRushStatementRunner$1.next(AndroidRushStatementRunner.java:70)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:53)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.implementation.ReflectionClassLoader$1.doAction(ReflectionClassLoader.java:183)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.implementation.ReflectionClassLoader.doLoop(ReflectionClassLoader.java:257)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.implementation.ReflectionClassLoader.addChildrenToList(ReflectionClassLoader.java:158)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:63)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.implementation.ReflectionClassLoader.loadClasses(ReflectionClassLoader.java:42)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.RushCore.load(RushCore.java:551)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.RushCore.load(RushCore.java:225)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.RushSearch.find(RushSearch.java:40)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at co.uk.rushorm.core.RushSearch.findSingle(RushSearch.java:31)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ at focalys.android_avh.connection.AvhWS$3.onGetListeGabaritsConnectionCompleted(AvhWS.java:71)
05-13 10:49:09.459    9887-9887/focalys.avh_android W/System.err﹕ ... 16 more
```
And I am sure about the int. Its value is 3

**Comment by Stuart-campbell** [comment]
What does the class look like? Also what os and device is it crashing on? 

Thanks

**Comment by PaulineBAUDOUIN** [comment]
I'm on a samsung galaxy Tab 3. 
My method is:
``` java
public void onGetGabaritAvhWSCompleted(int idGab) {
        System.out.println( idGab); // displays 3

        try {
            Gabarit gabTest = new RushSearch().whereEqual("identifier", idGab).findSingle(Gabarit.class);
            System.out.println("preuve:" + (gabTest == null)); // displays false
        } catch (Exception e){
            e.printStackTrace();
        }

    }
```
Do you need more information ?

**Comment by Stuart-campbell** [comment]
Can you share the Gabarit. Then I can have a go at reproducing the error.

Thanks

**Comment by PaulineBAUDOUIN** [comment]
Here is the full Gabarit:
```java
package focalys.android_avh.models;


import org.json.JSONException;
import org.json.JSONObject;

import java.util.List;

import co.uk.rushorm.core.RushObject;
import co.uk.rushorm.core.RushSearch;
import focalys.android_avh.connection.JsonData;

/**
 * Created by plauine on 08/04/15.
 */
public class Gabarit extends RushObject{
    public int identifier;
    public String description;
    public int img;
    public String name;
    public int vlength; // Durée d'enregistrement (entre 2 et 5s)
    public int gif;
    public String gifFromRest;
    public String imageFromRest;


    //public Maquette maquette;
    //public ArrayList<ProjetData> projetDatas;

    public Gabarit(){}

    public String toString(){
        return "Gabarit n°" + identifier
                + "\n - description: " + description
                + "\n - nom: " + name
                + "\n - longueur: " + vlength;
    }

    public int getNewIdentifier(){
        List<Gabarit> tous = new RushSearch().find(Gabarit.class);
        return tous.size() + 1;
    }

    /**
     * Regarde avec rush orm si l'objet d'id x existe,
     * si oui on le récupère et on le met a jour sinon on en créer et on le sauvegarde
     * @param data
     * @return
     */
    // a Implémenter
    public static int parse(JsonData data, int idMaq) {
        Gabarit newGab = new Gabarit();
        try {
            JSONObject obj = data.getJSONObject("data").getJSONObject("Template");
            Maquette maq = new RushSearch().whereEqual("identifier", idMaq).findSingle(Maquette.class);

            boolean found = false;
            int i = 0;
            while (!found && i < maq.gabarits.size()){
                if(maq.gabarits.get(i).identifier == obj.getInt("id")){
                    newGab = maq.gabarits.get(i);
                    newGab.identifier = obj.getInt("id");
                    newGab.description = obj.getString("description");
                    newGab.imageFromRest = obj.getString("image");
                    newGab.name = obj.getString("name");
                    newGab.vlength =  obj.getInt("vlength");
                    newGab.gifFromRest = obj.getString("gif");
                    newGab.save();
                    found = true;
                } else {
                    i++;
                }
            }

        } catch (JSONException e) {
            e.printStackTrace();
        }
        return newGab.identifier;
    }
}
```

**Comment by Stuart-campbell** [comment]
If you remove 

    public int img;
    public int gif;

Do you still get the error?

**Comment by PaulineBAUDOUIN** [comment]
Yes I do

**Comment by Stuart-campbell** [comment]
Are any of the strings likely to be very long?
