### ISSUE TITLE
RushOrm init fails with java.lang.NoClassDefFoundError: Failed resolution of: javax/lang/model/element/ElementKind

### ISSUE THREAD

**Issue by mrsasha** [Stuart-campbell/RushOrm#4]
Hi, I've been trying to integrate the RushOrm but it fails when opening the app. I have added the jar, init to Application and some settings to manifest, nothing else. Here's the log of the app opening and a  stacktrace. 

*log*

`02-13 13:52:33.002  24266-24266/com.mbrace.android.alpha D/ActivityThread? handleBindApplication:com.mbrace.android.alpha
02-13 13:52:33.002  24266-24266/com.mbrace.android.alpha D/ActivityThread? setTargetHeapUtilization:0.75
02-13 13:52:33.002  24266-24266/com.mbrace.android.alpha D/ActivityThread? setTargetHeapMinFree:2097152
02-13 13:52:33.262  24266-24266/com.mbrace.android.alpha E/RushOrm? android.support.v4.app.ActivityCompat21$SharedElementCallbackImpl
02-13 13:52:33.262  24266-24266/com.mbrace.android.alpha I/art? Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.ActivityCompat21$SharedElementCallbackImpl>
02-13 13:52:33.302  24266-24266/com.mbrace.android.alpha E/RushOrm? android.support.v4.app.FragmentTransitionCompat21$1
02-13 13:52:33.302  24266-24266/com.mbrace.android.alpha E/RushOrm? android.support.v4.app.FragmentTransitionCompat21$3
02-13 13:52:33.322  24266-24266/com.mbrace.android.alpha I/art? Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.FragmentTransitionCompat21$1>
02-13 13:52:33.322  24266-24266/com.mbrace.android.alpha I/art? Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.app.FragmentTransitionCompat21$3>
02-13 13:52:33.402  24266-24266/com.mbrace.android.alpha E/RushOrm? android.support.v4.media.VolumeProviderCompatApi21$1
02-13 13:52:33.422  24266-24266/com.mbrace.android.alpha E/RushOrm? android.support.v4.media.session.MediaControllerCompatApi21$CallbackProxy
02-13 13:52:33.432  24266-24266/com.mbrace.android.alpha E/RushOrm? android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy
02-13 13:52:33.482  24266-24266/com.mbrace.android.alpha E/RushOrm? android.support.v4.view.ViewCompatApi21$1
02-13 13:52:33.482  24266-24266/com.mbrace.android.alpha I/art? Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompatApi21$1>
02-13 13:52:33.532  24266-24266/com.mbrace.android.alpha E/RushOrm? android.support.v4.widget.DrawerLayoutCompatApi21$InsetsListener
02-13 13:52:33.532  24266-24266/com.mbrace.android.alpha I/art? Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.widget.DrawerLayoutCompatApi21$InsetsListener>
02-13 13:52:33.712  24266-24266/com.mbrace.android.alpha I/art? Rejecting re-init on previously-failed class java.lang.Class<com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner>
02-13 13:52:33.712  24266-24266/com.mbrace.android.alpha E/RushOrm? com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner$BridgeTestRunner$1
02-13 13:52:33.712  24266-24266/com.mbrace.android.alpha E/RushOrm? com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner$BridgeTestRunner
02-13 13:52:34.002  24266-24266/com.mbrace.android.alpha W/nalizableReferenceQueue? Could not load Finalizer in its own class loader.Loading Finalizer in the current class loader instead. As a result, you will not be ableto garbage collect this class loader. To support reclaiming this class loader, eitherresolve the underlying issue, or move Google Collections to your system class path.
    java.io.FileNotFoundException: com/google/common/base/internal/Finalizer.class
            at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.getBaseUrl(FinalizableReferenceQueue.java:261)
            at com.google.common.base.FinalizableReferenceQueue$DecoupledLoader.loadFinalizer(FinalizableReferenceQueue.java:245)
            at com.google.common.base.FinalizableReferenceQueue.loadFinalizer(FinalizableReferenceQueue.java:165)
            at com.google.common.base.FinalizableReferenceQueue.<clinit>(FinalizableReferenceQueue.java:88)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:305)
            at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:58)
            at co.uk.rushorm.android.AndroidRushClassFinder.getDomainClasses(AndroidRushClassFinder.java:45)
            at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:36)
            at co.uk.rushorm.core.RushCore.createTables(RushCore.java:184)
            at co.uk.rushorm.core.RushCore.initialize(RushCore.java:62)
            at co.uk.rushorm.core.RushCore.initialize(RushCore.java:53)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:35)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:21)
            at com.mbrace.android.MbraceApplication.onCreate(MbraceApplication.java:71)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
02-13 13:52:34.002  24266-24266/com.mbrace.android.alpha I/Finalizer? Couldn't access Thread.inheritableThreadLocals. Reference finalizer threads will inherit thread local values.
02-13 13:52:34.942  24266-24266/com.mbrace.android.alpha D/AndroidRuntime? Shutting down VM`

*stacktrace*

`02-13 13:52:34.942  24266-24266/com.mbrace.android.alpha E/AndroidRuntime? FATAL EXCEPTION: main
    Process: com.mbrace.android.alpha, PID: 24266
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/lang/model/element/ElementKind;
            at dagger.internal.codegen.GraphAnalysisInjectBinding$1.<clinit>(GraphAnalysisInjectBinding.java:60)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:305)
            at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:58)
            at co.uk.rushorm.android.AndroidRushClassFinder.getDomainClasses(AndroidRushClassFinder.java:45)
            at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:36)
            at co.uk.rushorm.core.RushCore.createTables(RushCore.java:184)
            at co.uk.rushorm.core.RushCore.initialize(RushCore.java:62)
            at co.uk.rushorm.core.RushCore.initialize(RushCore.java:53)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:35)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:21)
            at com.mbrace.android.MbraceApplication.onCreate(MbraceApplication.java:71)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.lang.model.element.ElementKind" on path: DexPathList[[zip file "/data/app/com.mbrace.android.alpha-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.mbrace.android.alpha-2, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at dagger.internal.codegen.GraphAnalysisInjectBinding$1.<clinit>(GraphAnalysisInjectBinding.java:60)
            at java.lang.Class.classForName(Native Method)
            at java.lang.Class.forName(Class.java:305)
            at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:58)
            at co.uk.rushorm.android.AndroidRushClassFinder.getDomainClasses(AndroidRushClassFinder.java:45)
            at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:36)
            at co.uk.rushorm.core.RushCore.createTables(RushCore.java:184)
            at co.uk.rushorm.core.RushCore.initialize(RushCore.java:62)
            at co.uk.rushorm.core.RushCore.initialize(RushCore.java:53)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:35)
            at co.uk.rushorm.android.RushAndroid.initialize(RushAndroid.java:21)
            at com.mbrace.android.MbraceApplication.onCreate(MbraceApplication.java:71)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
    Suppressed: java.lang.ClassNotFoundException: javax.lang.model.element.ElementKind
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 23 more
     Caused by: java.lang.NoClassDefFoundError: Class "Ljavax/lang/model/element/ElementKind;" not found
            ... 27 more`

**Comment by Stuart-campbell** [comment]
Hi,

Is this with 0.5.0 or 0.6.0?

Thanks

**Comment by mrsasha** [comment]
0.6.0. I also tried it with the cloned project, but no dice. 

BTW, the phone is One Plus One with Cyanogen 4.4.4 and I also tried it on the Samsung Galaxy S2 4.1.1 and Nexus 7 2013 4.4.4 Genymotion images.

**Comment by Stuart-campbell** [comment]
Can you run the example app?

**Comment by Stuart-campbell** [comment]
If you want a quick fix while I try to get to the bottom of this bug, you can add your own initialize function which replaces the code with the problem in.

    public static void initialize(Context context, final List<Class> classes) {
      Context applicationContext = context.getApplicationContext();

    RushConfig rushConfig = new AndroidRushConfig(applicationContext);
    RushStringSanitizer rushStringSanitizer = new AndroidRushStringSanitizer();
    RushStatementRunner statementRunner = new AndroidRushStatementRunner(applicationContext, rushConfig.dbName(), rushConfig.dbVersion());
    RushQueProvider queProvider = new AndroidRushQueProvider();
    Logger logger = new AndroidLogger();

    RushCore.initialize(new RushClassFinder() {
        @Override
        public List<Class> findClasses(RushConfig rushConfig) {
            return classes;
        }
    }, statementRunner, queProvider, rushConfig, rushStringSanitizer, logger, new ArrayList<RushColumn>());
    }
Then call as below. (This would actually be faster in the long run, just need to make sure you add all the classes you need)

    List<Class> classes = new ArrayList<>();
    classes.add(FirstRushClass.class);
    classes.add(SecondRushClass.class);
    initialize(getContext(), classes);

**Comment by mrsasha** [comment]
Thanks, it doesn't crash now.

**Comment by Stuart-campbell** [comment]
The problem is rushorm finds all your classes by loading a string of everything in your dex, then loading them with ClassForName. Then it checks if they extend Rush.

Because this process loops through every class it is actually just highlighting a problem else where in your project, which you have not seem before because the problem class is not used anywhere else.

I'm now catching Throwable so hopefully this will stop rushorm setting this crash off but it might be worth seeing if you can solve the root problem as your likely to see it again.

http://stackoverflow.com/questions/34413/why-am-i-getting-a-noclassdeffounderror-in-java

Thanks

**Comment by mrsasha** [comment]
Thanks for the info. Unfortunately, I'm trying to integrate this in an already existing projects that uses around 15 libraries, so now to try and debug all of them would take too much time.
