### ISSUE TITLE
No DB update on second run

### ISSUE THREAD

**Issue by GerhardPue** [Stuart-campbell/RushOrm#5]
// I have a service with a List<>

    @RushList(classname = "com.app.gerpue.sturmgraznews.rss.RssItem")
    List<RssItem> rssItems = null;

// add different Items to List

rssItems.add ...........

// save to DB .... but on second run ... nothing happens

RushCore.getInstance().save(rssItems);

// get Items from db and  the new one lack

 List<RssItem> objects = new RushSearch().find(RssItem.class);

// RssItem.class

public class RssItem extends RushObject {

    private String title;
    private String link;
    private String pubDate;
    private String autor;
    private String autorimage;
    private String imageUrl;

    public RssItem(String title, String link, String pubDate, String autor, String autorimage, String imageUrl) {
        this.title = title;
        this.link = link;
        this.pubDate = pubDate;
        this.autor = autor;
        this.autorimage = autorimage;
        this.imageUrl = imageUrl;
    }

    public String getTitle() {        return title   }
    public String getLink() {        return link;    }
    public String getPublicationDate() {        return pubDate;    }
    public String getAutor() {        return autor;    }
    public String getAutorimage() {        return autorimage;    }
    public String getImageUrl() {        return imageUrl;    }

    public RssItem() {    }
}

// Manifest

 
        <meta-data android:name="news_db_version" android:value="1" />

        
        <meta-data android:name="news_db_name" android:value="news.db" />

        
        <meta-data android:name="Rush_debug" android:value="false" />

        
        <meta-data android:name="Rush_requires_table_annotation" android:value="false" />

**Comment by Stuart-campbell** [comment]
Hi,

Think I have found the problem. Does this test encapsulate the issue correctly?

    public void testSaveThenUpdate() throws Exception {
        List<TestObject> objects = new ArrayList<>();
        objects.add(new TestObject());

        RushCore.getInstance().save(objects);

        List<TestObject> loadedObjects = new RushSearch().find(TestObject.class);
        loadedObjects.add(new TestObject());

        RushCore.getInstance().save(loadedObjects);

        List<TestObject> loadedObjects2 = new RushSearch().find(TestObject.class);
        assertTrue(loadedObjects2.size() == 2);
    }

Also you only actually need to annotate list type if its a field on a RushObject.

Thanks

**Comment by Stuart-campbell** [comment]
Let me know if 0.7.0 fixes this issue.

Thanks

**Comment by GerhardPue** [comment]
When I run the Test in the ApplicationTest.class

Running tests
Test running started
android.database.sqlite.SQLiteException: no such table: rush_com_myapp_TestObject (code 1): , while compiling: SELECT id FROM rush_com_myapp_TestObject ORDER BY id DESC LIMIT 1
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
at co.uk.rushorm.android.AndroidRushStatementRunner.runGetLastId(AndroidRushStatementRunner.java:35)
at co.uk.rushorm.core.RushCore$6.lastIdInTable(RushCore.java:231)
at co.uk.rushorm.core.implementation.ReflectionStatementGenerator.createObjects(ReflectionStatementGenerator.java:286)
at co.uk.rushorm.core.implementation.ReflectionStatementGenerator.generateSaveOrUpdate(ReflectionStatementGenerator.java:170)
at co.uk.rushorm.core.RushCore.save(RushCore.java:222)
at co.uk.rushorm.core.RushCore.save(RushCore.java:93)
at com.myapp.ApplicationTest.testSaveThenUpdate(ApplicationTest.java:28)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)

Finish

TestObject.class


public class TestObject extends RushObject {
    private String stingone = ("One");
    private String stingtwo = ("Two");
    private String stingthree = ("Three");
 
    public TestObject(){}
}

No 0.7.0 didn't fix the problem.... and I dont need to call ???
"  @RushList(classname = "com.myapp.rss.RssItem" ) "

**Comment by Stuart-campbell** [comment]
That problem is the table doesn't exsit. Setting debug to true in the manifest will fix that issue. I have added the test to the project so you don't need to run it. I was just wondering if the test covered your problem.

The list annotation is for saving a list of children in a rushObject. So only required if the list is a field on another rushObject.

Do you still have the original issue with 0.7?

**Comment by GerhardPue** [comment]
now this is the logcat:

android.database.sqlite.SQLiteException: no such table: rush_com_myapp_rss_RssItem (code 1): , while compiling: SELECT id FROM rush_com_myapp_rss_RssItem ORDER BY id DESC LIMIT 1
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
            at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
            at co.uk.rushorm.android.AndroidRushStatementRunner.runGetLastId(AndroidRushStatementRunner.java:35)
            at co.uk.rushorm.core.RushCore$6.lastIdInTable(RushCore.java:231)
            at co.uk.rushorm.core.implementation.ReflectionStatementGenerator.createObjects(ReflectionStatementGenerator.java:286)
            at co.uk.rushorm.core.implementation.ReflectionStatementGenerator.generateSaveOrUpdate(ReflectionStatementGenerator.java:170)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:222)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:93)
            at com.myapp.rss.RssService.onHandleIntent(RssService.java:134)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)

RssService.java 134 = RushCore.getInstance().save(rssItems);

**Comment by GerhardPue** [comment]
codesnippet:
// save
Log.d("RSSItemlast 1", rssItems.get(0).getPublicationDate() + rssItems.get(0).getAutor()  );
        RushCore.getInstance().save(rssItems);

// load

List<RssItem> objects = new RushSearch().find(RssItem.class);
        if(objects.size() != 0) {
            Log.d("DBRssItemlast 1", objects.get(0).getPublicationDate() + objects.get(0).getAutor());
        }

// and logcat:

02-14 23:17:33.476  31766-31830/com.myapp.sturmgraznews D/RSSItemlast 1? Sat, 14 Feb 2015 22:40:58 +0100 Laola1
02-14 23:17:33.643  31766-31830/com.myapp.sturmgraznews D/DBRssItemlast 1? Sat 14 Feb 2015 14:36:39 GMT+01:00 Facebook

**Comment by Stuart-campbell** [comment]
The list is not guaranteed to be loaded in the same order as its saved. RushSearch can be ordered by a field.

If you print out all the items or count can you check if the new item is saved?

**Comment by GerhardPue** [comment]
/ New Installation first Run

 // first Run		 Items 			pubDate					Source
D/RSSItemlast 	   50     	        Sun 15 Feb 2015 08:15:01 GMT 	Facebook
D/DBRssItemlast        50     	        Sun 15 Feb 2015 08:15:01 GMT 	Facebook
// second run
D/RSSItemlast            50 	         Sun 15 Feb 2015 08:15:01 GMT 	Facebook
D/DBRssItemlast 1?   100 		Sun 15 Feb 2015 08:15:01 GMT 	Facebook
// third run	
D/RSSItemlast 1? 	    50 		Sun 15 Feb 2015 08:15:01 GMT 	Facebook
D/DBRssItemlast 1?   150 		Sun 15 Feb 2015 08:15:01 GMT 	Facebook
// fourth run
D/RSSItemlast 1? 	     50 		Sun 15 Feb 2015 08:15:01 GMT 	Facebook
D/DBRssItemlast 1?   200 		Sun 15 Feb 2015 08:15:01 GMT 	Facebook

every time the Items get addet to DB  ...

**Comment by Stuart-campbell** [comment]
How do you create the first 50 objects? It looks like you might be redoing that every run.

If your able to post a bit more code I can see if I can understand the issue.

**Comment by GerhardPue** [comment]
// My RssService.Class
public class RssService {
  List<RssItem> rssItems = null;

    public RssService() {
        super("RssService");
    }

    public void onCreate() {
        super.onCreate();
        mContext = getApplicationContext();
      

    }

    @Override
    protected void onHandleIntent(Intent intent) {




        try {
		
            RssHandler parser = new RssHandler();
            RssKeyHandler parsing = new RssKeyHandler();
            FacebookHanlder readFb = new FacebookHanlder();
            Log.i(Constants.TAG, "Parsing startet");

           
            rssItems = parser.parse(getInputStream(RSS_LINK_2);
            rssItems.addAll(parser.parse(getInputStream(RSS_LINK_5));
            rssItems.addAll(readFb.parse(RSS_LINK_4);
            rssItems.addAll(parsing.parse(getInputStream(RSS_Link_10));
            rssItems.addAll(parsing .parse(getInputStream(RSS_Link_11));
            rssItems.addAll(parsing.parse(getInputStream(RSS_Link_12));
        
            Collections.sort(rssItems, new CustomComparator());


        } catch (XmlPullParserException e) {
            Log.w(e.getMessage(), e);
        } catch (IOException e) {
            Log.w(e.getMessage(), e);
        }

        Log.d("RSSItemlast 1", rssItems.size() + rssItems.get(0).getPublicationDate() + rssItems.get(0).getAutor()  );
        RushCore.getInstance().save(rssItems);

        

       logAction();
    }



    public void  logAction (){

        List<RssItem> objects = new RushSearch().orderAsc("id").find(RssItem.class);
        if(objects.size() != 0) {
            Log.d("DBRssItemlast 1", objects.size() + objects.get(0).getPublicationDate() + objects.get(0).getAutor());
        }
    }
}

**Comment by Stuart-campbell** [comment]
It looks like onHandleIntent you are saving all your received items again.

An update is only done on an already saved object.

So your parser could check the database to see if that object is already saved then update it else create a new one.

Example based on title being unique.

    String parsedTitle = /* get title */

    RssItem rssItem = new RushSearch().whereEqual("title", parsedTitle).findSingle(RssItem.class);
    if(rssItem != null) {
     /* Update */
    }else {
     /* Create new */
    }

     objects.add(rssItem);
     RushCore.getInstance().save(rssItems);

Or more simple you could just delete all the items in the db when you get the new set and resave everything.

**Comment by GerhardPue** [comment]
//  Ok ... i get an Error ... when i clean the DB with 
 List<RssItem> items = new RushSearch().find(RssItem.class);
        if (items.size() != 0) {

            RushCore.getInstance().delete(rssItems); <-----------error
        }

  java.lang.NullPointerException
            at co.uk.rushorm.core.implementation.ReflectionStatementGenerator.generateDelete(ReflectionStatementGenerator.java:427)
            at co.uk.rushorm.core.RushCore.delete(RushCore.java:250)
            at co.uk.rushorm.core.RushCore.delete(RushCore.java:136)
            at com.myapp.rss.RssService.onHandleIntent(RssService.java:113)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)

and nothing of this ways is the best ...

the best way would be ... Save all New Items to DB and Clean DB .... for example...from Items (14 days old) ..and holt min 50 last Items in DB

**Comment by Stuart-campbell** [comment]
It would be fairly easy to implement that logic, as you can save date fields.

Also your problem above is rssItems is null. You want to delete items.

Calling save will create a new object if not yet saved other wise it will update. That's why there is no update method.

**Comment by GerhardPue** [comment]
Sorry for this mistakes (I thinking from another world  ;-) ) .... now it works with delete ....... but i will change it later to check if Item exists and delete at a Datefield
