### ISSUE TITLE
SQL Error when updating objects

### ISSUE THREAD

**Issue by nis73** [Stuart-campbell/RushOrm#7]
First, thanks for your great work. I'm planning to use your framework for my next app. 
I'm having the following issue: When I create objects with parent-child relationship, store them, load them again, change something and store them again the framework crashes with a SQL Error. See the following minimal working example:

    public class Child extends RushObject {

        private String string;

        public Child(String string) {
            this.string = string;
        }

        public Child() {
        }

        public String getString() {
            return string;
        }

        public void setString(String string) {
            this.string = string;
        }
    }

    public class Parent extends RushObject {

        @RushList(classname = "de.test.testrushorm.Child")
        private List<Child> children;

        public Parent() {
            this.children = new ArrayList<Child>();
        }

        public boolean add(Child child) {
            return children.add(child);
        }

        public boolean remove(Child child) {
            return children.remove(child);
        }

        public List<Child> getChildren() {
            return children;
        }
    }

    public class MainActivity extends ActionBarActivity {

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);

            Parent parent = new Parent();
            parent.save();

            Child firstChild = new Child();
            firstChild.save();

            Child secondChild = new Child();
            secondChild.save();

            parent.add(firstChild);
            parent.add(secondChild);
            parent.save();

            parent = new RushSearch().find(Parent.class).get(0);
            parent.getChildren().get(0).setString("test1");
            parent.save();

        }
    }

Stacktrace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{de.test.testrushorm/de.test.testrushorm.MainActivity}: co.uk.rushorm.core.exceptions.RushSqlException: This is most likely caused by a change in data structure or new RushObject.
    This issue should be resolved by a database migration.
    This can be done by updating db version number in the manifest or setting Rush in debug mode.
    To set Rush in debug mode add this to your manifest file - <meta-data android:name="Rush_debug" android:value="true" />
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2103)
            at android.app.ActivityThread.access$600(ActivityThread.java:137)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4827)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: co.uk.rushorm.core.exceptions.RushSqlException: This is most likely caused by a change in data structure or new RushObject.
    This issue should be resolved by a database migration.
    This can be done by updating db version number in the manifest or setting Rush in debug mode.
    To set Rush in debug mode add this to your manifest file - <meta-data android:name="Rush_debug" android:value="true" />
            at co.uk.rushorm.android.AndroidRushStatementRunner.runRaw(AndroidRushStatementRunner.java:35)
            at co.uk.rushorm.core.RushCore$6.createdOrUpdateStatement(RushCore.java:238)
            at co.uk.rushorm.core.implementation.ReflectionStatementGenerator$3.doAction(ReflectionStatementGenerator.java:366)
            at co.uk.rushorm.core.implementation.ReflectionStatementGenerator.doLoop(ReflectionStatementGenerator.java:73)
            at co.uk.rushorm.core.implementation.ReflectionStatementGenerator.updateObjects(ReflectionStatementGenerator.java:342)
            at co.uk.rushorm.core.implementation.ReflectionStatementGenerator.generateSaveOrUpdate(ReflectionStatementGenerator.java:169)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:224)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:95)
            at co.uk.rushorm.core.RushCore.save(RushCore.java:90)
            at co.uk.rushorm.core.RushObject.save(RushObject.java:10)
            at de.test.testrushorm.MainActivity.onCreate(MainActivity.java:30)
            at android.app.Activity.performCreate(Activity.java:5013)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2042)
            ... 11 more

The error seems to be related to the creation of the sql update statements. Any ideas? Did I do something wrong?

**Comment by Stuart-campbell** [comment]
Can you confirm you have this set to true in your manifest?

 <meta-data android:name="Rush_debug" android:value="true" />

Also as a side note, you do not need to save the children first, saving the parent object takes care of that for you.

**Comment by nis73** [comment]
Thanks for the hint.
Here's my manifest:

    <application
        android:name=".TestApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">

        
        <meta-data android:name="Rush_db_version" android:value="3" />
        
        <meta-data android:name="Rush_db_name" android:value="rush.db" />
        
        <meta-data android:name="Rush_debug" android:value="true" />
        
        <meta-data android:name="Rush_requires_table_annotation" android:value="false" />

        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

**Comment by Stuart-campbell** [comment]
Ok, can I also confirm you are using v0.8.0? Obstructing the underlying SQL error was a mistake which ill be updating soon.

**Comment by nis73** [comment]
Yes, I used v0.8.0 with this example. Yesterday I was using v0.7.0 and got a more expressive log output, stating an invalid sql update statement of the form 
    UPDATE <Table> SET field="value1" WHERE id=1, SET field="value2" WHERE id=2

**Comment by Stuart-campbell** [comment]
If you add just a random extra field to the parent does that fix it?

**Comment by nis73** [comment]
I added an extra String field to the parent, but unfortunately it still crashes with the same exception

**Comment by Stuart-campbell** [comment]
Are you classes inner classes?

**Comment by nis73** [comment]
No, these are normal classes

**Comment by Stuart-campbell** [comment]
I have reproduced your crash, I think I already have a fix on another branch which is basically ready to integrate so should be fixed very soon.

Thanks for you patience.

**Comment by Stuart-campbell** [comment]
Should be fixed now with version 1.0.0, will require a clean install though. Let me know if it works.

Thanks

**Comment by nis73** [comment]
Thanks a lot for your quick fix. It works now!
