### ISSUE TITLE
Error accessing native library in ART

### ISSUE THREAD

**Issue by ajhool** [Stuart-campbell/RushOrm#77]
I ran into an error on certain devices when using RushORM as a library. The app ran correctly on my Galaxy S4 with 4.4.2, but failed on my Nexus 7 with 5.1.1. The error occurs when I initialize Rush. The Nexus 7 stacktrace is long and includes a lot of native log statements, so I have included what I believe are the two main areas of interest below. Let me know if you want the whole thing.

Top of the stacktrace:
```
E/RushOrm﹕ android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1
E/art﹕ Command not implemented: REQUEST: VirtualMachine.HoldEvents (length=11 id=0x0007ef)
E/art﹕ [ 09-15 20:22:17.127  1168: 1185 E/art      ]
    Command not implemented: REQUEST: VirtualMachine.ReleaseEvents (length=11 id=0x000a44)
E/art﹕ [ 09-15 20:22:17.623  1168: 1197 I/art      ]
Background sticky concurrent mark sweep GC freed 17492(2MB) AllocSpace objects, 0(0B) LOS objects, 9% free, 18MB/19MB, paused 2.075ms total 102.020ms
E/RushOrm﹕ com.mongodb.DBPort$ScramSha1Authenticator$ScramSha1SaslClient
E/RushOrm﹕ Native library (com/sun/jna/android-arm/libjnidispatch.so) not found in resource path (.)
A/art﹕ art/runtime/class_linker.cc:4690] Check failed: super_class->IsResolved()
A/art﹕ art/runtime/runtime.cc:289] Runtime aborting...
A/art﹕ art/runtime/runtime.cc:289] Aborting thread:
A/art﹕ art/runtime/runtime.cc:289] "main" prio=5 tid=1 Runnable
A/art﹕ art/runtime/runtime.cc:289]   | group="" sCount=0 dsCount=0 obj=0x736e3000 self=0xb4827800
A/art﹕ art/runtime/runtime.cc:289]   | sysTid=1168 nice=0 cgrp=default sched=0/0 handle=0xb6f63bec
A/art﹕ art/runtime/runtime.cc:289]   | state=R schedstat=( 0 0 0 ) utm=299 stm=22 core=1 HZ=100
A/art﹕ art/runtime/runtime.cc:289]   | stack=0xbe029000-0xbe02b000 stackSize=8MB
A/art﹕ art/runtime/runtime.cc:289]   | held mutexes= "abort lock" "mutator lock"(shared held)
A/art﹕ art/runtime/runtime.cc:289]   native: #00 pc 00004e64  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
```

Another area of interest further down the stacktrace:

```
A/art﹕ art/runtime/runtime.cc:289]   native: #16 pc 000d9e75  /system/lib/libart.so (art::ClassLinker::FindClassInPathClassLoader(art::ScopedObjectAccessAlreadyRunnable&, art::Thread*, char const*, unsigned int, art::Handle<art::mirror::ClassLoader>)+536)
A/art﹕ art/runtime/runtime.cc:289]   native: #17 pc 000da1e7  /system/lib/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>) (.part.415)+462)
A/art﹕ art/runtime/runtime.cc:289]   native: #18 pc 00207365  /system/lib/libart.so (art::Class_classForName(_JNIEnv*, _jclass*, _jstring*, unsigned char, _jobject*)+196)
A/art﹕ art/runtime/runtime.cc:289]   native: #19 pc 0005ff95  /data/dalvik-cache/arm/system@framework@boot.oat (Java_java_lang_Class_classForName__Ljava_lang_String_2ZLjava_lang_ClassLoader_2+136)
A/art﹕ art/runtime/runtime.cc:289]   at java.lang.Class.classForName!(Native method)
A/art﹕ art/runtime/runtime.cc:289]   at java.lang.Class.forName(Class.java:309)
A/art﹕ art/runtime/runtime.cc:289]   at co.uk.rushorm.android.AndroidRushClassFinder.getRushClass(AndroidRushClassFinder.java:58)
A/art﹕ art/runtime/runtime.cc:289]   at co.uk.rushorm.android.AndroidRushClassFinder.getRushClasses(AndroidRushClassFinder.java:45)
A/art﹕ art/runtime/runtime.cc:289]   at co.uk.rushorm.android.AndroidRushClassFinder.findClasses(AndroidRushClassFinder.java:36)
A/art﹕ art/runtime/runtime.cc:289]   at co.uk.rushorm.core.RushCore.loadAnnotationCache(RushCore.java:462)
A/art﹕ art/runtime/runtime.cc:289]   at co.uk.rushorm.core.RushCore.initialize(RushCore.java:122)
A/art﹕ art/runtime/runtime.cc:289]   at co.uk.rushorm.core.RushCore.initialize(RushCore.java:80)
A/art﹕ art/runtime/runtime.cc:289]   at com.myapp.MyApp.onCreate(Portol.java:55)
```

**Comment by aldefy** [comment]
5 days no reply ? i cant run this orm in my app, 3rd project , this is just sad , no resolve for this problem

**Comment by Stuart-campbell** [comment]
Sorry on my holidays.

Have you tried what's suggested here?

http://www.rushorm.com/advanced.html#Troubleshooting

Thanks

**Comment by aldefy** [comment]
Thanks , i was following up on other such issues and their solution, let me retest and get back , i have OnePlus two , tested on nexus 4 as well some problem with the jni lib or sorts on lollipop

**Comment by aldefy** [comment]
It worked , for any one else this is what it should look like : 
 List<Class<? extends Rush>> classes = new ArrayList<>();
        // Add classes
        classes.add(Model.class);

        AndroidInitializeConfig config = new AndroidInitializeConfig(getApplicationContext());
        config.setClasses(classes);
        RushCore.initialize(config);
    }

**Comment by elenaGuoAi** [comment]
hello, sir, I have the same error, but I can't open the following URL:(http://www.rushorm.com/advanced.html#Troubleshooting), Could you please post the solution or send it to my emailbox: 307151196@qq.com,Thank you,very much!
