### ISSUE TITLE
ClassLoader Problem with FaceBook SDK

### ISSUE THREAD

**Issue by splitbrain** [Stuart-campbell/RushOrm#83]
As soon as I inititalize the RushORM library in my Application, it crashed with a class not found exception for the FaceBook SDK classes.

Without 

```
AndroidInitializeConfig config = new AndroidInitializeConfig(getApplicationContext());
RushCore.initialize(config);
```

everything works (no rush is used, yet).

But as soon as those lines are in I get the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: de.xxx.android.yyy, PID: 13745
E/AndroidRuntime: java.lang.NoClassDefFoundError: com/facebook/share/widget/ShareDialog
E/AndroidRuntime:     at de.xxx.android.yyy.GuiPlayerManager.<init>(GuiPlayerManager.java:91)
E/AndroidRuntime:     at de.xxx.android.yyy.activity.MainActivity.onCreate(MainActivity.java:88)
E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5312)
E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2541)
E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2641)
E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:156)
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5867)
E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.share.widget.ShareDialog" on path: DexPathList[[zip file "/data/app/de.xxx.android.radio.rtl1046-2.apk"],nativeLibraryDirectories=[/data/app-lib/de.xxx.android.radio.rtl1046-2, /vendor/lib, /system/lib]]
E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime:     at de.xxx.android.yyy.GuiPlayerManager.<init>(GuiPlayerManager.java:91) 
E/AndroidRuntime:     at de.xxx.android.yyy.activity.MainActivity.onCreate(MainActivity.java:88) 
E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5312) 
E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2541) 
E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2641) 
E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:156) 
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355) 
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:157) 
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5867) 
E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674) 
E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
W/ActivityThread: ClassLoader.loadClass: The class loader returned by Thread.getContextClassLoader() may fail for processes that host multiple applications. You should explicitly specify a context class loader. For example: Thread.setContextClassLoader(getClass().getClassLoader());
```

I thought the last last line about the Thread's classloader might be related but the debugging method suggested in http://stackoverflow.com/questions/13407006/android-class-loader-may-fail-for-processes-that-host-multiple-applications gave no further hints.

Any idea what's going on?

**Comment by Stuart-campbell** [comment]
Hi,

This should sort your problem out for you. It caused by the way it loops through your classes to find which ones extend Rush. Easy to resolve by just setting the Rush classes on the config. Which currently would be an empty list. 

http://www.rushorm.com/advanced.html#Troubleshooting

Thanks

**Comment by splitbrain** [comment]
Hmm that seems like the right solution but I'm having trouble to apply it.

I now got a ```public class Favorite extends RushObject``` so I guess I have to add ```Favorite``` to the list of classes. I figured out that there's a new missing in the example code but somehow the signatures still don't match:

```
List<Class<Rush>> classes = new ArrayList<>();
classes.add(Favorite.class);
AndroidInitializeConfig config = new AndroidInitializeConfig(getApplicationContext());
config.setClasses(classes);
RushCore.initialize(config);
```

These are the errors I get:

```
Error:(43, 16) error: no suitable method found for add(Class<Favorite>)
method List.add(Class<Rush>) is not applicable
(actual argument Class<Favorite> cannot be converted to Class<Rush> by method invocation conversion)
method List.add(int,Class<Rush>) is not applicable
(actual and formal argument lists differ in length)
Error:(46, 15) error: method setClasses in class RushInitializeConfig cannot be applied to given types;
required: List<Class<? extends Rush>>
found: List<Class<Rush>>
reason: actual argument List<Class<Rush>> cannot be converted to List<Class<? extends Rush>> by method invocation conversion
```

Do I need to do any Type conversion here?

**Comment by Stuart-campbell** [comment]
I think you want 

    List<Class<? extends Rush>> classes = new ArrayList<>();

Looks like a error in the documentation.
